# Generated by Django 5.2.11 on 2026-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
