# Generated by Django 5.2.11 on 2026-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_word_is_rejected_word_rejected_at_word_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
