# Generated by Django 6.0.3 on 2026-03-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_chapter_name_word_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='word',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='word',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rejected_by',
        ),
        migrations.DeleteModel(
            name='WordCheckerSkip',
        ),
    ]
