# Generated by Django 5.2.11 on 2026-03-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_word_class_name_chapter_is_rejected_is_approved_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CheckerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('updated_and_approved', 'Updated and Approved'), ('rejected', 'Rejected'), ('removed_for_me', 'Removed For Me')], max_length=32)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_checker_actions', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checker_actions', to='words.word')),
            ],
            options={
                'db_table': 'words_checker_action',
                'ordering': ['-action_at'],
                'unique_together': {('word', 'user')},
            },
        ),
        migrations.AddField(
            model_name='word',
            name='checked_by',
            field=models.ManyToManyField(blank=True, related_name='checked_words', through='words.CheckerAction', to=settings.AUTH_USER_MODEL),
        ),
    ]
